namespace MyDhathuru.Domain.Enums;

public enum BusinessAuditActionType
{
    SupplierCreated = 1,
    SupplierUpdated = 2,
    SupplierDeleted = 3,
    ExpenseCategoryCreated = 4,
    ExpenseCategoryUpdated = 5,
    ExpenseCategoryDeleted = 6,
    ReceivedInvoiceCreated = 7,
    ReceivedInvoiceUpdated = 8,
    ReceivedInvoiceDeleted = 9,
    ReceivedInvoicePaymentRecorded = 10,
    ReceivedInvoiceAttachmentUploaded = 11,
    PaymentVoucherCreated = 12,
    PaymentVoucherUpdated = 13,
    PaymentVoucherApproved = 14,
    PaymentVoucherPosted = 15,
    PaymentVoucherCancelled = 16,
    PaymentVoucherDeleted = 17,
    ExpenseEntryCreated = 18,
    ExpenseEntryUpdated = 19,
    ExpenseEntryDeleted = 20,
    RentEntryCreated = 21,
    RentEntryUpdated = 22,
    RentEntryDeleted = 23,
    StaffConductFormCreated = 24,
    StaffConductFormUpdated = 25,
    BptMappingRuleUpdated = 26,
    ExchangeRateCreated = 27,
    ExchangeRateUpdated = 28,
    ExchangeRateDeleted = 29,
    SalesAdjustmentCreated = 30,
    SalesAdjustmentUpdated = 31,
    SalesAdjustmentDeleted = 32,
    OtherIncomeEntryCreated = 33,
    OtherIncomeEntryUpdated = 34,
    OtherIncomeEntryDeleted = 35,
    BptAdjustmentCreated = 36,
    BptAdjustmentUpdated = 37,
    BptAdjustmentDeleted = 38,
    StaffConductDhivehiSaved = 39,
    StaffConductDhivehiPdfGenerated = 40
}
